export const DEMO_USER = {
  id: "demo-user",
  full_name: "Alex Morgan",
  email: "demo.reviewer@scoutygo.app",
  role: "user",
  subscription_tier: "Pro",
  created_date: "2024-09-15T10:00:00.000Z",
};

const now = Date.now();
const h = 3600000;

export const DEMO_SIGNALS = [
  {
    id: "demo-001",
    title: "Marina Heights Tower Launches Off-Plan Sales",
    category: "Real Estate", type: "Real Estate",
    company: "Vantage Development Group", entity_name: "Vantage Development Group",
    location: "Dubai, UAE", country: "UAE", city: "Dubai",
    time_ago: "2h ago", detected_timestamp: now - 2 * h,
    created_date: new Date(now - 2 * h).toISOString(),
    confidence: 92,
    summary: "Vantage Development Group has initiated off-plan sales for a 45-story residential tower in Dubai Marina, targeting Q3 2026 completion.",
    explanation: "Off-plan launch detected via developer registration filings and broker network activity. The project includes 320 units with configurations ranging from 1 to 3 bedrooms. Early-bird pricing suggests competitive positioning against nearby comparable developments.",
    signals: ["New Market Entry", "Infrastructure Project", "Lease Acquisition"],
    timeline: "6-12 months", marketSize: "$180M",
    sourceType: "Public Registry", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "RESIDENTIAL", transactionType: "OFF_PLAN_SALE", developmentStage: "PRE_LAUNCH" },
    isNew: true,
  },
  {
    id: "demo-002",
    title: "Riyadh Mixed-Use Development Breaks Ground",
    category: "Real Estate", type: "Mixed-Use",
    company: "Al Noor Real Estate", entity_name: "Al Noor Real Estate",
    location: "Riyadh, Saudi Arabia", country: "Saudi Arabia", city: "Riyadh",
    time_ago: "4h ago", detected_timestamp: now - 4 * h,
    created_date: new Date(now - 4 * h).toISOString(),
    confidence: 88,
    summary: "Groundbreaking ceremony held for a $420M mixed-use development spanning residential, retail, and office space across 12 buildings.",
    explanation: "Construction permit filed and approved. The development spans 180,000 sqm and includes 850 residential units, 40,000 sqm retail, and 60,000 sqm Grade A office space. Phase 1 delivery targeted for Q1 2027.",
    signals: ["Infrastructure Project", "New Market Entry"],
    timeline: "12-18 months", marketSize: "$420M",
    sourceType: "Planning Portal", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "MIXED_USE", transactionType: "DEVELOPMENT", developmentStage: "CONSTRUCTION_STARTED" },
    isNew: true,
  },
  {
    id: "demo-003",
    title: "Sovereign Wealth Fund Acquires Commercial Portfolio",
    category: "Investment", type: "Investment",
    company: "Gulf Capital Partners", entity_name: "Gulf Capital Partners",
    location: "Doha, Qatar", country: "Qatar", city: "Doha",
    time_ago: "6h ago", detected_timestamp: now - 6 * h,
    created_date: new Date(now - 6 * h).toISOString(),
    confidence: 85,
    summary: "Gulf Capital Partners completes acquisition of a 6-building commercial portfolio for $310M, expanding its Doha CBD holdings.",
    explanation: "Transaction recorded via property registry. The portfolio comprises 240,000 sqm of Grade A office space across the West Bay district. Acquisition price reflects a 7.2% gross yield, suggesting a long-term income strategy.",
    signals: ["Funding Activity", "Market Reconnaissance"],
    timeline: "3-6 months", marketSize: "$310M",
    sourceType: "Property Registry", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-004",
    title: "International Franchise Brand Enters Saudi Market",
    category: "Business", type: "Franchise",
    company: "BlueOcean F&B Group", entity_name: "BlueOcean F&B Group",
    location: "Jeddah, Saudi Arabia", country: "Saudi Arabia", city: "Jeddah",
    time_ago: "8h ago", detected_timestamp: now - 8 * h,
    created_date: new Date(now - 8 * h).toISOString(),
    confidence: 79,
    summary: "BlueOcean F&B Group signs master franchise agreement for 25 locations across Saudi Arabia, starting with Jeddah and Riyadh.",
    explanation: "Commercial registration filed for the master franchise entity. Initial locations targeted in prime retail malls and standalone drive-thru formats. The brand's entry aligns with Saudi Vision 2030's tourism and entertainment sector growth.",
    signals: ["New Market Entry", "Partnership Announced"],
    timeline: "6-12 months", marketSize: "$45M",
    sourceType: "Commercial Registry", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "SINGLE_SOURCE",
    isNew: false,
  },
  {
    id: "demo-005",
    title: "Abu Dhabi Industrial Zone Announces Phase 2 Expansion",
    category: "Real Estate", type: "Industrial",
    company: "KEZAD Group", entity_name: "KEZAD Group",
    location: "Abu Dhabi, UAE", country: "UAE", city: "Abu Dhabi",
    time_ago: "12h ago", detected_timestamp: now - 12 * h,
    created_date: new Date(now - 12 * h).toISOString(),
    confidence: 90,
    summary: "Khalifa Economic Zones Abu Dhabi announces Phase 2 expansion with 4.1 sqkm of new industrial land and pre-built warehouse facilities.",
    explanation: "Master plan amendment published. The expansion adds 52 pre-built warehouse units (ranging from 2,500 to 15,000 sqm) and 18 light industrial plots. Pre-leasing activity has reportedly reached 40% prior to formal launch.",
    signals: ["Infrastructure Project", "Supply Chain Signal"],
    timeline: "6-12 months", marketSize: "$220M",
    sourceType: "Government Gazette", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "INDUSTRIAL", transactionType: "LEASE", developmentStage: "PRE_CONSTRUCTION" },
    isNew: false,
  },
  {
    id: "demo-006",
    title: "Tech Startup Closes Series B Funding Round",
    category: "Investment", type: "Investment",
    company: "PropTech Innovations", entity_name: "PropTech Innovations",
    location: "Dubai, UAE", country: "UAE", city: "Dubai",
    time_ago: "14h ago", detected_timestamp: now - 14 * h,
    created_date: new Date(now - 14 * h).toISOString(),
    confidence: 83,
    summary: "PropTech Innovations secures $65M in Series B funding led by regional venture capital, valuing the company at $340M post-money.",
    explanation: "Filing detected via corporate registry updates. The round includes participation from two international VC firms and a sovereign wealth fund. Capital is earmarked for MENA market expansion and AI product development.",
    signals: ["Funding Activity", "Executive Movement"],
    timeline: "3-6 months", marketSize: "$65M",
    sourceType: "Corporate Filing", verificationStatus: "VERIFIED",
    freshnessState: "FRESH", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-007",
    title: "London Office Tower Refurbishment Approved",
    category: "Real Estate", type: "Real Estate",
    company: "Meridian Properties", entity_name: "Meridian Properties",
    location: "London, United Kingdom", country: "United Kingdom", city: "London",
    time_ago: "18h ago", detected_timestamp: now - 18 * h,
    created_date: new Date(now - 18 * h).toISOString(),
    confidence: 76,
    summary: "Planning permission granted for a £140M refurbishment of a 28-story office tower in the City of London, targeting ESG compliance.",
    explanation: "Planning approval published by the City of London Corporation. The project includes full facade replacement, net-zero carbon retrofit, and reconfiguration of 48,000 sqm of office space. Targeted completion is Q4 2026.",
    signals: ["Infrastructure Project", "Regulatory Filing"],
    timeline: "12-18 months", marketSize: "$178M",
    sourceType: "Planning Portal", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "OFFICE", transactionType: "REFURBISHMENT", developmentStage: "PLANNING_APPROVED" },
    isNew: false,
  },
  {
    id: "demo-008",
    title: "Singapore Logistics Firm Expands Regional Hub",
    category: "Business", type: "Expansion",
    company: "PacificLog Solutions", entity_name: "PacificLog Solutions",
    location: "Singapore", country: "Singapore", city: "Singapore",
    time_ago: "22h ago", detected_timestamp: now - 22 * h,
    created_date: new Date(now - 22 * h).toISOString(),
    confidence: 81,
    summary: "PacificLog Solutions signs 10-year lease for a 60,000 sqm logistics facility, establishing its Southeast Asia regional headquarters.",
    explanation: "Lease agreement recorded. The facility includes automated warehousing, cold chain capabilities, and cross-docking infrastructure. The expansion signals a strategic shift to serve growing e-commerce demand across ASEAN markets.",
    signals: ["Lease Acquisition", "New Market Entry", "Supply Chain Signal"],
    timeline: "3-6 months", marketSize: "$32M",
    sourceType: "Corporate Announcement", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "SINGLE_SOURCE",
    isNew: false,
  },
  {
    id: "demo-009",
    title: "Doha Hospitality Project Secures Financing",
    category: "Real Estate", type: "Hospitality",
    company: "Pearl Hospitality Holdings", entity_name: "Pearl Hospitality Holdings",
    location: "Doha, Qatar", country: "Qatar", city: "Doha",
    time_ago: "1d ago", detected_timestamp: now - 26 * h,
    created_date: new Date(now - 26 * h).toISOString(),
    confidence: 74,
    summary: "Pearl Hospitality Holdings closes $95M Shariah-compliant financing for a 250-key luxury resort on The Pearl-Qatar.",
    explanation: "Financing agreement registered. The project includes a 5-star hotel, 120 branded residences, and 8,000 sqm of retail and F&B. Construction tender expected to be issued within 60 days.",
    signals: ["Funding Activity", "Infrastructure Project"],
    timeline: "12-18 months", marketSize: "$95M",
    sourceType: "Corporate Filing", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "HOSPITALITY", transactionType: "DEVELOPMENT", developmentStage: "FINANCING_SECURED" },
    isNew: false,
  },
  {
    id: "demo-010",
    title: "Mumbai Infrastructure SPV Formed for Transit Project",
    category: "Investment", type: "Public Sector & Procurement",
    company: "MetroInfra Consortium", entity_name: "MetroInfra Consortium",
    location: "Mumbai, India", country: "India", city: "Mumbai",
    time_ago: "1d ago", detected_timestamp: now - 30 * h,
    created_date: new Date(now - 30 * h).toISOString(),
    confidence: 86,
    summary: "Special purpose vehicle formed for a $580M metro transit extension, with contractor pre-qualification opening next quarter.",
    explanation: "SPV registration detected. The 18km extension includes 14 stations and a depot. Pre-qualification documents indicate opportunities for civil works, signaling, rolling stock, and electrical systems packages.",
    signals: ["Infrastructure Project", "Regulatory Filing", "Partnership Announced"],
    timeline: "12-18 months", marketSize: "$580M",
    sourceType: "Government Gazette", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-011",
    title: "Dubai Retail Group Announces 15-Store Expansion",
    category: "Business", type: "Expansion",
    company: "Emirates Retail Concepts", entity_name: "Emirates Retail Concepts",
    location: "Dubai, UAE", country: "UAE", city: "Dubai",
    time_ago: "2d ago", detected_timestamp: now - 50 * h,
    created_date: new Date(now - 50 * h).toISOString(),
    confidence: 78,
    summary: "Emirates Retail Concepts reveals plans to open 15 new stores across GCC malls over 18 months, backed by $28M capital deployment.",
    explanation: "Expansion plan published in investor briefing. Store formats range from 200 to 800 sqm across community malls and super-regional centers. The expansion targets high-growth demographics in Dubai, Abu Dhabi, and Riyadh.",
    signals: ["New Market Entry", "Hiring Expansion"],
    timeline: "12-18 months", marketSize: "$28M",
    sourceType: "Corporate Announcement", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "SINGLE_SOURCE",
    isNew: false,
  },
  {
    id: "demo-012",
    title: "Riyadh Concert Venue Development Tender Issued",
    category: "Real Estate", type: "Hospitality",
    company: "Riyadh Entertainment Group", entity_name: "Riyadh Entertainment Group",
    location: "Riyadh, Saudi Arabia", country: "Saudi Arabia", city: "Riyadh",
    time_ago: "2d ago", detected_timestamp: now - 54 * h,
    created_date: new Date(now - 54 * h).toISOString(),
    confidence: 84,
    summary: "Main contractor tender issued for a 20,000-capacity indoor concert and events venue, with a projected construction value of $160M.",
    explanation: "Tender notice published. The venue includes a retractable seating system, 12 VIP suites, and 4,000 sqm of F&B and retail. Subcontractor packages for MEP, acoustics, and specialized stage infrastructure expected by Q3.",
    signals: ["Infrastructure Project", "Regulatory Filing"],
    timeline: "12-18 months", marketSize: "$160M",
    sourceType: "Tender Portal", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "HOSPITALITY", transactionType: "TENDER", developmentStage: "CONTRACTOR_TENDER" },
    isNew: false,
  },
  {
    id: "demo-013",
    title: "Abu Dhabi Sovereign Fund Acquires Logistics Platform",
    category: "Investment", type: "Investment",
    company: "Capital Investment Authority", entity_name: "Capital Investment Authority",
    location: "Abu Dhabi, UAE", country: "UAE", city: "Abu Dhabi",
    time_ago: "3d ago", detected_timestamp: now - 74 * h,
    created_date: new Date(now - 74 * h).toISOString(),
    confidence: 89,
    summary: "Capital Investment Authority acquires a pan-GCC last-mile logistics platform for $240M, integrating it into its supply chain portfolio.",
    explanation: "Acquisition filing registered. The platform operates 14 fulfillment centers across the UAE, Saudi Arabia, and Qatar with a total of 320,000 sqm of warehousing. The deal includes proprietary warehouse management technology.",
    signals: ["Funding Activity", "Market Reconnaissance", "Supply Chain Signal"],
    timeline: "3-6 months", marketSize: "$240M",
    sourceType: "Corporate Filing", verificationStatus: "VERIFIED",
    freshnessState: "RECENT", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-014",
    title: "New York Developer Files for Luxury Condo Project",
    category: "Real Estate", type: "Real Estate",
    company: "Manhattan Skyline Developments", entity_name: "Manhattan Skyline Developments",
    location: "New York, United States", country: "United States", city: "New York",
    time_ago: "3d ago", detected_timestamp: now - 78 * h,
    created_date: new Date(now - 78 * h).toISOString(),
    confidence: 72,
    summary: "Building permit application filed for a 52-story ultra-luxury condominium tower in Midtown Manhattan, with an estimated sell-out of $650M.",
    explanation: "Permit application submitted to NYC Department of Buildings. The project comprises 48 full-floor residences starting at $4.5M, with amenities including a private club, spa, and automated parking. Approval expected within 6-9 months.",
    signals: ["Regulatory Filing", "Infrastructure Project"],
    timeline: "12-18 months", marketSize: "$650M",
    sourceType: "Planning Portal", verificationStatus: "PENDING",
    freshnessState: "RECENT", corroborationState: "SINGLE_SOURCE",
    realEstateDetails: { assetType: "RESIDENTIAL", transactionType: "DEVELOPMENT", developmentStage: "PLANNING_SUBMITTED" },
    isNew: false,
  },
  {
    id: "demo-015",
    title: "Construction Materials Supplier Wins Mega-Project Contract",
    category: "Business", type: "Industrial",
    company: "BuildCore Materials", entity_name: "BuildCore Materials",
    location: "Riyadh, Saudi Arabia", country: "Saudi Arabia", city: "Riyadh",
    time_ago: "4d ago", detected_timestamp: now - 100 * h,
    created_date: new Date(now - 100 * h).toISOString(),
    confidence: 80,
    summary: "BuildCore Materials secures a $48M contract to supply ready-mix concrete and steel reinforcement for a major giga-project phase.",
    explanation: "Contract award notice published. The 3-year supply agreement covers approximately 1.2M cubic meters of concrete and 45,000 tonnes of rebar. The contract includes an exclusivity clause for Phases 2 and 3 of the development.",
    signals: ["Partnership Announced", "Supply Chain Signal"],
    timeline: "6-12 months", marketSize: "$48M",
    sourceType: "Corporate Announcement", verificationStatus: "VERIFIED",
    freshnessState: "AGING", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-016",
    title: "Singapore REIT Acquires European Office Portfolio",
    category: "Investment", type: "Investment",
    company: "AsiaPacific REIT Trust", entity_name: "AsiaPacific REIT Trust",
    location: "Singapore", country: "Singapore", city: "Singapore",
    time_ago: "5d ago", detected_timestamp: now - 120 * h,
    created_date: new Date(now - 120 * h).toISOString(),
    confidence: 75,
    summary: "AsiaPacific REIT Trust completes acquisition of a 7-property European office portfolio for €520M, diversifying into Frankfurt and Amsterdam.",
    explanation: "Transaction completed and registered. The portfolio comprises 285,000 sqm of Grade A office space with 94% occupancy and a weighted average lease expiry of 6.2 years. The acquisition increases the REIT's European allocation to 22%.",
    signals: ["Funding Activity", "Market Reconnaissance"],
    timeline: "3-6 months", marketSize: "$560M",
    sourceType: "Corporate Filing", verificationStatus: "VERIFIED",
    freshnessState: "AGING", corroborationState: "CORROBORATED",
    isNew: false,
  },
  {
    id: "demo-017",
    title: "Dubai Marina Branded Residences Project Announced",
    category: "Real Estate", type: "Real Estate",
    company: "Crystal Point Developers", entity_name: "Crystal Point Developers",
    location: "Dubai, UAE", country: "UAE", city: "Dubai",
    time_ago: "5d ago", detected_timestamp: now - 124 * h,
    created_date: new Date(now - 124 * h).toISOString(),
    confidence: 70,
    summary: "Crystal Point Developers announces a branded residences project with an international hospitality brand, comprising 180 units in Dubai Marina.",
    explanation: "Project announcement detected via developer marketing registration. The 40-story tower will feature 180 branded residences, a 150-key hotel component, and 5,000 sqm of retail. Pre-registration for brokers opens next month.",
    signals: ["New Market Entry", "Partnership Announced"],
    timeline: "6-12 months", marketSize: "$145M",
    sourceType: "Developer Filing", verificationStatus: "PENDING",
    freshnessState: "AGING", corroborationState: "SINGLE_SOURCE",
    realEstateDetails: { assetType: "RESIDENTIAL", transactionType: "OFF_PLAN_SALE", developmentStage: "ANNOUNCED" },
    isNew: false,
  },
  {
    id: "demo-018",
    title: "Doha Medical City Consultant Appointment",
    category: "Real Estate", type: "Real Estate",
    company: "Qatar Health Infrastructure", entity_name: "Qatar Health Infrastructure",
    location: "Doha, Qatar", country: "Qatar", city: "Doha",
    time_ago: "6d ago", detected_timestamp: now - 148 * h,
    created_date: new Date(now - 148 * h).toISOString(),
    confidence: 82,
    summary: "Lead consultant appointed for a 500-bed medical city development, with a total project value estimated at $380M.",
    explanation: "Consultant appointment notice published. The 240,000 sqm medical city includes a general hospital, specialist clinics, research facilities, and medical staff housing. The project is slated for design completion in 8 months, with construction tender to follow.",
    signals: ["Infrastructure Project", "Regulatory Filing", "Partnership Announced"],
    timeline: "12-18 months", marketSize: "$380M",
    sourceType: "Tender Portal", verificationStatus: "VERIFIED",
    freshnessState: "AGING", corroborationState: "CORROBORATED",
    realEstateDetails: { assetType: "HEALTHCARE", transactionType: "DEVELOPMENT", developmentStage: "CONSULTANT_APPOINTED" },
    isNew: false,
  },
];

export const DEMO_STATS = {
  totalOpportunities: DEMO_SIGNALS.length,
  countries: [...new Set(DEMO_SIGNALS.map((s) => s.country))].length,
  companies: [...new Set(DEMO_SIGNALS.map((s) => s.company))].length,
  recentSignals: DEMO_SIGNALS.filter((s) => s.detected_timestamp > now - 48 * h).length,
};